### ISSUE TITLE
Potential issue with To Get - Mike

### ISSUE THREAD

**Issue by Mike-j-t** [Mike-j-t/Shopper#36]
It is possible (I believe) that **To Get** fails if it encounters a **Store** without any **Aisles**. 

Although a default Aisle is added if user selects No to add an Aisle to a new Store. It is possible to use back button to skip and thus a Store without and Aisle would be created.

2 Potential fixes are;
a) On dialog cancel (back) create a default if the Store was added without an Aisle.
b) In To Get initially check for any Stores that have no Aisles and add Aisles.

**Comment by Mike-j-t** [comment]
Note sure this is an issue. Doesn't appear to be one. Leaving open just in case.

**Comment by Mike-j-t** [comment]
Note this is an issue HOWEVER, the issue is when stocking i.e. in **AddProductToShopActivity** .

e.g.

> 05-26 17:18:33.548 30807-30807/mjt.shopper E/AndroidRuntime: FATAL EXCEPTION: main
>                                                              Process: mjt.shopper, PID: 30807
>                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{mjt.shopper/mjt.shopper.AddProductToShopActivity}: android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 0
>                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
>                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
>                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:151)
>                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
>                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                  at android.os.Looper.loop(Looper.java:135)
>                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
>                                                                  at java.lang.reflect.Method.invoke(Native Method)
>                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
>                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
>                                                               Caused by: android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 0
>                                                                  at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
>                                                                  at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
>                                                                  at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:74)
>                                                                  at mjt.shopper.AddProductToShopActivity.onCreate(AddProductToShopActivity.java:303)
>                                                                  at android.app.Activity.performCreate(Activity.java:5990)
>                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
>                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
>                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
>                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:151) 
>                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
>                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                  at android.os.Looper.loop(Looper.java:135) 
>                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254) 
>                                                                  at java.lang.reflect.Method.invoke(Native Method) 
>                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
>                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
>                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 

Options therefore are now;
a) in **`ShopAdd`**  activity, on dialog cancel (back) create a default if the Store was added without an Aisle.
b) In **`ShopAdd`**  activity,  create a default Aisle and don't even consider allowing the user to add and Aisle. 
c) In **`AddProductToShopActivity`** initially check for any Stores that have no Aisles and add default Aisles.
and Aisle. 

Should use **AislelessStoreIssue** as comment for this?

**Comment by Mike-j-t** [comment]
Oops closed issue. re-opening.

**Comment by Mike-j-t** [comment]
Took option B, removed entire dialog giving option and now always create an Aisle name "Default Aisle" when a Store is created.
